### ISSUE TITLE
[DOC] Add autodoc with magidoc

### ISSUE THREAD

**Issue by gxldCptRick** [Carrera-Dev-Consulting/zombie-nomnom-api#32]
** What is missing documentation **

We want docs to automagically build docs for graphql so we can improve the docs for the repo.

** Where have you tried to look **

** How it can be Improved **

**Comment by vCertxfiedGoat** [comment]
I tried to implement this but it resulted in a bunch of issues and it was more work than needed. Currently, there are no good solutions other than the local docs
